[package]
name = "crosvm"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[profile.release]
lto = true
panic = 'abort'

[dependencies]
io_jail = { path = "io_jail" }
kvm = { path = "kvm" }
sys_util = { path = "sys_util" }
x86_64 = { path = "x86_64" }
kernel_loader = { path = "kernel_loader" }
libc = "0.2.21"
byteorder = "1"
syscall_defines = { path = "syscall_defines" }
net_sys = { path = "net_sys" }
net_util = { path = "net_util" }
vhost = { path = "vhost" }
virtio_sys = { path = "virtio_sys" }

[dependencies.clap]
version = "*"
default-features = false
