[package]
name = "plugin_proto"
version = "0.14.0"
authors = ["The Chromium OS Authors"]
build = "build.rs"

[dependencies]
protobuf = "*"
kvm_sys = { path = "../kvm_sys" }

[build-dependencies]
gcc = "=0.3.54"
protoc-rust = "=1.4.3"
