[package]
name = "plugin_proto"
version = "0.10.0"
authors = ["The Chromium OS Authors"]
build = "build.rs"

[dependencies]
protobuf = "*"

[build-dependencies]
gcc = "=0.3.54"
protoc-rust = "=1.4.3"
