[package]
name = "usbdev"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
assertions = { path = "../assertions" }
data_model = { path = "../data_model" }
sync = { path = "../sync" }
