[package]
name = "x86_64"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
arch = { path = "../arch" }
data_model = { path = "../data_model" }
devices = { path = "../devices" }
kvm_sys = { path = "../kvm_sys" }
kvm = { path = "../kvm" }
sys_util = { path = "../sys_util" }
resources = { path = "../resources" }
kernel_cmdline = { path = "../kernel_cmdline" }
kernel_loader = { path = "../kernel_loader" }
libc = "*"
byteorder = "*"
