[package]
name = "arch"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
devices = { path = "../devices" }
device_manager = { path = "../device_manager" }
kvm = { path = "../kvm" }
sys_util = { path = "../sys_util" }
kernel_cmdline = { path = "../kernel_cmdline" }
libc = "*"
