[package]
name = "msg_on_socket_derive"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
syn = "=0.12"
quote = "=0.4"
proc-macro2 = "=0.2"

[lib]
proc-macro = true
path = "msg_on_socket_derive.rs"
