[package]
name = "msg_on_socket_derive"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
syn = "=0.15"
quote = "=0.6"
proc-macro2 = "=0.4"

[lib]
proc-macro = true
path = "msg_on_socket_derive.rs"
