[package]
name = "msg_socket"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
msg_on_socket_derive = { path = "msg_on_socket_derive" }
sys_util = { path = "../sys_util"  }
data_model = { path = "../data_model" }
