[package]
name = "sys_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
data_model = { path = "../data_model" }
libc = "*"
syscall_defines = { path = "../syscall_defines" }
poll_token_derive = { path = "poll_token_derive" }
