[package]
name = "sys_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
include = ["src/**/*", "Cargo.toml"]

[dependencies]
data_model = "*"
libc = "*"
syscall_defines = "*"
poll_token_derive = "*"
sync = "*"

[workspace]

[patch.crates-io]
poll_token_derive = { path = "poll_token_derive" }
